object Versions {
    const val gradlePluginVersion = "7.1.2"
    const val kotlinVersion = "1.6.20"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val jvmVersion = "1.8"
    const val jUnitVersion = "4.+"
    const val coreKtxVersion = "1.7.0"
    const val testJunitVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val navigationVersion = "2.4.2"
    const val hiltVersion = "2.41"
    const val lifecycleVersion = "2.4.1"
    const val glideVersion = "4.13.0"
    const val sdpVersion = "1.0.6"
    const val sspVersion = "1.0.6"
    const val agcVersion = "1.6.5.300"
    const val cloudDBVersion = "1.5.0.300"
    const val ktorVersion = "1.1.4"
}